include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Ignore these while you iterate; fix them properly soon.
    depend_on_referenced_packages: ignore
    avoid_print: info # make prints a non-fatal info
    empty_constructor_bodies: ignore
    deprecated_member_use: info
    file_names: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    use_full_hex_values_for_flutter_colors: ignore
    use_super_parameters: ignore
    curly_braces_in_flow_control_structures: ignore
    prefer_interpolation_to_compose_strings: ignore
    invalid_override_different_default_values_named: ignore
