name: Flutter CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - 'feature-*'
  workflow_dispatch:

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

  test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --coverage

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    # Only run the heavy release build automatically for main.
    # But workflow_dispatch (manual) runs will still execute this job.
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk
